spring.application.name=reservas-backend
spring.data.mongodb.uri=mongodb+srv://mariamontilladiaz_db_user:Alejapreciosa_27@cluster0.j6a6yzn.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=reservasdb

server.port=8080

jwt.secret=Ks82Jf9aPqL0xA7bN3dC6QwR8zM1vT4gH9kY2uF5sE0rB3tC
jwt.expiration=86400000
