spring.data.mongodb.uri=mongodb+srv://mariamontilladiaz_db_user:Alejapreciosa_27@cluster0.asre4g3.mongodb.net/vehiculos?appName=Cluster0
server.port=8080
logging.level.org.mongodb.driver=WARN
spring.data.mongodb.read-preference=secondaryPreferred